### ISSUE TITLE
ENHANCEMENT - News theme should use breadcrumbs

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#272]
This has come up before on Slack, but this issue is to swap the "News" header with the breadcrumbs; this does a few things:

- brings the News child theme in line with the VF components (and EMBL patterns?) 
- improves semantics by no longer having two `<h1>`s on the page
- uses the breadcrumbs so we can highlight things related to the current news article

Here's what it would feel like:

- embl.org/news
![image](https://user-images.githubusercontent.com/928100/81156803-9c5dbd00-8f86-11ea-998f-769a5d06d4fb.png)

- https://www.embl.org/news/science/responding-to-health-threats-posed-by-coronaviruses/
  ![image](https://user-images.githubusercontent.com/928100/81156268-10e42c00-8f86-11ea-8296-12fa29ac25fe.png)

## Implementing it

We'd need to split this out into a few parts of work.

1. (easy) Drop the existing `vf-masthead` and replace with the `embl-breadcrumbs-lookup`:
  ```html
  <nav class="vf-breadcrumbs embl-breadcrumbs-lookup" aria-label="Breadcrumb" data-embl-js-breadcrumbs-lookup>
    <div class="vf-list vf-list--inline | vf-breadcrumbs__list | embl-breadcrumbs-lookup--ghosting"></div>
  </nav> 
  ```

2. (easy) Create a "Press office" EMBL.org profile in the contentHub and make that the global embl:who

3. (unsure how tricky) For individual news posts, the related `embl:where` and `embl:who` would need to be individually specified

**Comment by dbushell** [comment]
Ideally the breadcrumbs container would be part of the template:

```html
<!-- wp:vf/container-global-header /-->

<!-- wp:vf/container-breadcrumbs /-->

<!-- wp:vf/container-page-template /-->

<!-- wp:vf/container-global-footer /-->
```
First I need to implement a way for child themes to define their default template without relying on a deployment script.

The breadcrumbs container uses meta tags in the head:

```html
<meta name="embl:what" content="Web Development" uuid="f67d1b53-b7d5-43e0-aa5c-8db3965fb3fc">
<meta name="embl:active" content="what">
```

At present these are global settings from the [EMBL Taxonomy plugin](https://github.com/visual-framework/vf-wp/blob/master/wp-content/plugins/embl-taxonomy/includes/settings.php#L243). It would be easy to add an `apply_filters` hook there. Then child themes could override on a per-post basis.

I would suggest following Ken's steps above for now. Instead of hard-coding HTML we could use the plugin:

```php
if (class_exists('VF_Breadcrumbs')) {
  VF_Plugin::render(VF_Plugin::get_plugin('vf_breadcrumbs'));
}
```

The plugin template is the same as the HTML suggested.

Later we can remove this and add to the template.

**Comment by kasprzyk-sz** [comment]
News theme uses the breadcrumbs plugin now.

Press office profile has also been created: 
https://content.embl.org/node/28524
