### ISSUE TITLE
BUG - EMBL Group roles - unable to change author to EMBL roles

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-wp#297]
Hi David,

Sandeep might have mentioned this to you last week, but as I don't see an issue here thought it might be better to place one.

It's not possible to change author of a post to someone assigned to an EMBL Group role, be it Admin or Editor. Other WP default roles show up on the list, but not EMBL Group role ones.

Also, the list of users might grow to be quite large. Could you also see what would be the better option to have the author field handle a large user base?

Thank you :)

**Comment by sandykadam** [comment]
Hi Filipe

THis is already fixed by David but that tag is not yet deployed on all group sites. As per process we first deploy to Dummy sites to check if anything is breaking and then release on all group sites but we haven't yet released on all group sites. Also news/documents/shop/press/files these are all individual sites apart from group sites. They need to deployed separately.
Having said that I just deployed latest tag on DEV News, so can you please check this issue on DEV, if all ok then we can deploy on production

**Comment by filipe-dias** [comment]
Hi Sandeep

Those are good news.
I just tried with News dev and it worked great. :+1: 
News doesn't use the Group Roles btw. The site I would really like to have is [dev Communications](https://wwwdev.embl.org/groups/communications), to fix the blog posts that were migrated last week.

Thanks. Closing this issue

**Comment by sandykadam** [comment]
Oh yes comms is part of group site which is not yet deployed, once deployed I will post msg on slack.
