### ISSUE TITLE
ENHANCEMENT - vf-tabs Gutenberg support

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#325]
Would be useful to be able to support vf-tabs in the Gutenberg editor. 

https://visual-framework.github.io/vf-core/components/detail/vf-tabs.html

It might be two parts:

1. A Gutenberg block for the `.vf-tabs`
1. A Gutenberg container block (similar to vf-grid) for the `.vf-tabs-content`

This may need to wait for David to be back?

**Comment by kasprzyk-sz** [comment]
As for the container - do you mean that it should have an option for a full width layout?

![Screenshot 2020-06-02 at 09 29 19](https://user-images.githubusercontent.com/54020899/83492449-94c10380-a4b3-11ea-89f0-34ede2cd57ce.png)

or something else?

**Comment by khawkins98** [comment]
Full width would be good, but mostly meant that you need to be able to put other things inside the tabs container ... paragraphs, vf-box and potentially even a vf-grid inside a `.vf-tabs-content`

**Comment by sturobson** [comment]
> paragraphs, vf-box and potentially even a vf-grid inside a .vf-tabs-content

this will be fun to get right responsively - for every eventuality :sob:

We should also look at the `vf-tabs` pattern in `vf-core` and maybe do something like this - 

https://codepen.io/sturobson/full/xgfeI

**Comment by kasprzyk-sz** [comment]
Added the vf-tabs block in #344. It uses ACF WYSIWYG field, so at this point it doesn't allow to add a grid or other blocks inside `.vf-tabs-content`. ACF doesn't offer block nesting option and I'm not sure how to make it work, so I guess that any further enhancement needs to wait for David 😄

**Comment by dbushell** [comment]
ACF now supports nested "Inner Blocks" as of [ACF v5.9.0](https://www.advancedcustomfields.com/blog/acf-5-9-0-release-inner-blocks-ui-improvements-and-exciting-features/)

However it's limited to one `<InnerBlocks />` per block so we can't use it in a repeater field for example (to replace the WYSIWYG field for each tab). That's actually a limitation of Gutenberg itself. 

I'm still experimenting, but I think the only solution for `vf-tabs` is using React instead of ACF. Similar to how `vf-grid` and `vf-grid-column` work. One parent block that has child blocks for `vf-tabs__section` that each have their own `<InnerBlocks />`. It's more complicated than grid/columns because the `vf-tabs__list` exists above the children. I need to wrap my head around how that fits together in the parent block.

**Comment by dbushell** [comment]
New `vf-tabs` block that uses React instead of ACF for full `<InnerBlocks/>` support.

<img width="1015" alt="Screenshot 2020-09-30 at 14 11 03" src="https://user-images.githubusercontent.com/998922/94689484-731b4000-031e-11eb-8c99-6127a18e2acb.png">

**Comment by dbushell** [comment]
First version has been merged. Technicaly it allows nested tabs in the sense that it allows any inner blocks. There is an open [`vf-core`](https://github.com/visual-framework/vf-core/issues/1136) issue for nested blocks.
