### ISSUE TITLE
Add support fo vf-social-links component as gutenberg block

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#474]
Adding social icons to a page is a frequent request and other solutions often do not work well. 

We have the [`vf-social-links` component](https://visual-framework.github.io/vf-core//components/vf-social-links/index.html?q=social) and should make use of it.

It may also sense to have this available as a container as well.

**Comment by sturobson** [comment]
The `vf-social-links` component in `vf-core` is quite 'rigid' at the moment - I'll make necessary changes so that it's more malleable (although in `vf-wp` I guess this point is actually moot as PHP will be taking up some of the strain).

Also -- we should do some research and try and work out what we are going to do with 'all the icons' for everything. As, as it stands the `vf-social-links` SVG will be on every page that uses it -- perhaps it being an external cached file is a better way to go.

**Comment by khawkins98** [comment]
Some related thinking on icon handling at https://github.com/visual-framework/vf-core/issues/751#issuecomment-594417259

**Comment by dbushell** [comment]
Worth noting that WordPress has a "Social Icons" block:

<img width="442" alt="Screenshot 2020-09-14 at 10 21 17" src="https://user-images.githubusercontent.com/998922/93068255-bf525900-f66b-11ea-8d7c-756908169465.png">

It supports a lot of website icons, handles all the inline SVG, and the editor UI is decent.

It'd be easy to style to match the VF. That does mean custom CSS in the WP themes and ignoring the VF pattern HTML for the most part (maybe a way to include/extend some Sass to avoid duplicate styles).

From my experience I don't think it's worth fighting WP on this one, a custom social block wouldn't be as user-friendly as the "native block". Restyling would be the lesser evil and easier to maintain in my opinion.

**Comment by dbushell** [comment]
Further testing reveals the `wp-block-social-links` markup is similar enough to `vf-social-links` that we could do a find/replace block transform in PHP.

![Screenshot 2020-09-24 at 09 02 55](https://user-images.githubusercontent.com/998922/94118276-d7c92d00-fe3c-11ea-99b6-62ca764e138e.png)

The WordPress SVG icons are also 24×24 same as the Visual Framework which is a nice.

Problem is WP uses sightly different versions. Facebook for example uses the round white circle with the "F" cut out, rather than the white "F" of the VF version.

I suppose we could also find/replace that line SVG but I don't like the idea of that.

**Comment by kasprzyk-sz** [comment]
That looks good and surely is more friendly and intuitive in the editor. One thing we need to keep in mind is, that we're going to use social icons on non wordpress sites as well. That means the icons need to have a consistent look.
